### ISSUE TITLE
OrganisationTypeEnum mismatch

### ISSUE THREAD

**Issue by dldobbin** [XeroAPI/Xero-Java#153]
The list of Organisation Types from https://developer.xero.com/documentation/api/types
is different than in OrganisationTypeEnum.

Specifically, I'm getting an error when calling getOrganisations due to the returned Organisation having type 'SOLE_TRADER' whereas the Enum has 'SOLETRADER'. 

`Caused by: com.xero.api.XeroApiException: Can not construct instance of com.xero.models.accounting.Organisation$OrganisationTypeEnum, problem: Unexpected value 'SOLE_TRADER'`

**Comment by SidneyAllen** [comment]
Hi @dldobbin 

Thanks for the feedback.  Fixed in version 2.3.14

**Comment by dldobbin** [comment]
@SidneyAllen 

The same issue still exists for OrganisationEntityTypeEnum

**Comment by SidneyAllen** [comment]
@dldobbin - changes applied to OrganisationEntityTypeEnum and deployed as version 2.3.15
